name: Build and Push Docker Image

on:
  push:
    branches:
      - main
    paths:
      - 'Dockerfile'
      - 'entrypoint.sh'
      - '.github/workflows/build-image.yml'
      - 'assets/**'
      - 'test-action.sh'
  workflow_dispatch:  # Allow manual trigger
    inputs:
      push_image:
        description: 'Push the built image to the registry'
        type: boolean
        default: true
      tag:
        description: 'Additional tag for the image (optional)'
        required: false
        type: string

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        if: ${{ github.event_name != 'workflow_dispatch' || github.event.inputs.push_image == 'true' }}
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/takutakahashi/goose-action
          tags: |
            type=raw,value=latest,enable=${{ github.event_name != 'workflow_dispatch' || github.event.inputs.push_image == 'true' }}
            type=sha,format=short
            type=raw,value=${{ github.event.inputs.tag }},enable=${{ github.event.inputs.tag != '' }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'workflow_dispatch' || github.event.inputs.push_image == 'true' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      
      - name: Image digest
        run: echo "Image digest is ${{ steps.build.outputs.digest }}"
      
      - name: Summary
        run: |
          echo "## Docker Image Build" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          if [ "${{ github.event_name != 'workflow_dispatch' || github.event.inputs.push_image == 'true' }}" = "true" ]; then
            echo "✅ Image pushed to registry with tags: ${{ steps.meta.outputs.tags }}" >> $GITHUB_STEP_SUMMARY
          else
            echo "ℹ️ Image built but not pushed to registry" >> $GITHUB_STEP_SUMMARY
          fi