name: Test Docker Image Build

on:
  pull_request:
    paths:
      - 'Dockerfile'
      - 'entrypoint.sh'
      - '.github/workflows/build-image.yml'
      - 'assets/**'

jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Build image (no push)
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64
          push: false
          tags: goose-action-test:pr-${{ github.event.pull_request.number }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      
      - name: Basic image test
        run: |
          docker build -t goose-action-test:${{ github.event.pull_request.number }} .
          echo "::group::Image info"
          docker image inspect goose-action-test:${{ github.event.pull_request.number }}
          echo "::endgroup::"
          echo "::group::Test entrypoint.sh presence"
          docker run --rm goose-action-test:${{ github.event.pull_request.number }} ls -la /entrypoint.sh
          echo "::endgroup::"
          echo "::group::Test goose binary"
          docker run --rm goose-action-test:${{ github.event.pull_request.number }} /root/.local/bin/goose --version
          echo "::endgroup::"